name = "tutortron"
main = "server.js"
compatibility_date = "2024-01-01"

[build]
command = "npm install && npm run build"

# Custom domain configuration
[env.production]
routes = [
  { pattern = "tutor-tron.com/*", zone_id = "your_zone_id" }
]

# KV namespaces
[[kv_namespaces]]
binding = "TEACHERS"
id = "5c97959983ca46f1a72169649096f5ab"

[[kv_namespaces]]
binding = "FILES"
id = "409a826d6bf94a4f9bfc4af0929bfdab"

[site]
bucket = "./public"