name = "tutortron"
main = "server.js"
compatibility_date = "2023-11-21"

[build]
command = "npm install && npm run build"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "tutortron"
database_id = "78f92ab6-7ad7-43f4-9e08-e19b530c2211"